# Generated by Django 5.1.1 on 2025-11-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroDependencias',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('id_aud_sql', models.IntegerField(blank=True, db_column='ID_AUD_SQL', null=True)),
                ('id_aud_report', models.IntegerField(blank=True, db_column='ID_AUD_REPORT', null=True)),
                ('id_aud_fv', models.IntegerField(blank=True, db_column='ID_AUD_FV', null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_column='DATA_CRIACAO')),
                ('criado_por', models.IntegerField(blank=True, db_column='CRIADO_POR', null=True)),
            ],
            options={
                'db_table': 'Cadastro_Dependencias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoFV',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('nome', models.CharField(blank=True, db_column='NOME', max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('idcategoria', models.IntegerField(blank=True, db_column='IDCATEGORIA', null=True)),
                ('ativo', models.BooleanField(db_column='ATIVO', default=True)),
                ('prioridade', models.CharField(blank=True, db_column='PRIORIDADE', max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, db_column='OBSERVACAO', null=True)),
                ('lida', models.IntegerField(db_column='LIDA', default=0)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(blank=True, db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_FV',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoReport',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('codaplicacao', models.IntegerField(blank=True, db_column='CODAPLICACAO', null=True)),
                ('codigo', models.CharField(blank=True, db_column='CODIGO', max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, db_column='DESCRICAO', null=True)),
                ('prioridade', models.CharField(blank=True, db_column='PRIORIDADE', max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, db_column='OBSERVACAO', null=True)),
                ('lida', models.IntegerField(db_column='LIDA', default=0)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(blank=True, db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_REPORT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomizacaoSQL',
            fields=[
                ('codsentenca', models.IntegerField(db_column='CODSENTENCA', primary_key=True, serialize=False)),
                ('codcoligada', models.IntegerField(blank=True, db_column='CODCOLIGADA', null=True)),
                ('aplicacao', models.CharField(blank=True, db_column='APLICACAO', max_length=100, null=True)),
                ('titulo', models.CharField(blank=True, db_column='TITULO', max_length=255, null=True)),
                ('sentenca', models.TextField(blank=True, db_column='SENTENCA', null=True)),
                ('tamanho', models.IntegerField(blank=True, db_column='TAMANHO', null=True)),
                ('prioridade', models.CharField(blank=True, db_column='PRIORIDADE', max_length=50, null=True)),
                ('observacao', models.TextField(blank=True, db_column='OBSERVACAO', null=True)),
                ('lida', models.IntegerField(db_column='LIDA', default=0)),
                ('reccreatedby', models.CharField(blank=True, db_column='RECCREATEDBY', max_length=100, null=True)),
                ('reccreatedon', models.DateTimeField(blank=True, db_column='RECCREATEDON', null=True)),
                ('recmodifiedby', models.CharField(blank=True, db_column='RECMODIFIEDBY', max_length=100, null=True)),
                ('recmodifiedon', models.DateTimeField(blank=True, db_column='RECMODIFIEDON', null=True)),
            ],
            options={
                'db_table': 'AUD_SQL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='NOME', max_length=255)),
                ('email', models.CharField(db_column='EMAIL', max_length=255)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
    ]
