# Generated by Django 5.1.1 on 2025-11-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrodependencias',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], db_column='PRIORIDADE', default='Baixa', max_length=50, null=True),
        ),
    ]
